using System.Text.Json;
using System.Text.Json.Serialization;

namespace A2A;

/// <summary>
/// Represents an agent task that can be executed by an A2A agent.
/// </summary>
public class AgentTask : A2AResponse
{
    /// <summary>
    /// Gets or sets the unique identifier for the task.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonRequired]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the context identifier that groups related tasks together.
    /// </summary>
    [JsonPropertyName("contextId")]
    [JsonRequired]
    public string? ContextId { get; set; }

    /// <summary>
    /// Gets or sets the current status of the task.
    /// </summary>
    [JsonPropertyName("status")]
    [JsonRequired]
    public AgentTaskStatus Status { get; set; } = new AgentTaskStatus();

    /// <summary>
    /// Gets or sets the list of artifacts generated by the task.
    /// </summary>
    [JsonPropertyName("artifacts")]
    public List<Artifact>? Artifacts { get; set; }

    /// <summary>
    /// Gets or sets the message history associated with the task.
    /// </summary>
    [JsonPropertyName("history")]
    public List<Message>? History { get; set; } = [];

    /// <summary>
    /// Gets or sets additional metadata associated with the task.
    /// </summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, JsonElement>? Metadata { get; set; }
}