using System.Text.Json;
using System.Text.Json.Serialization;

namespace A2A;

/// <summary>
/// Represents an artifact that can be generated by an agent as part of task execution.
/// </summary>
public class Artifact
{
    /// <summary>
    /// Gets or sets the unique identifier for this artifact.
    /// </summary>
    [JsonPropertyName("artifactId")]
    [JsonRequired]
    public string ArtifactId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the human-readable name of the artifact.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Gets or sets a description of the artifact and its purpose.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>
    /// Gets or sets the content parts that make up this artifact.
    /// </summary>
    [JsonPropertyName("parts")]
    [JsonRequired]
    public List<Part> Parts { get; set; } = [];

    /// <summary>
    /// Gets or sets additional metadata associated with the artifact.
    /// </summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, JsonElement>? Metadata { get; set; }
}